name: 🐛 Bug report
description: Report a bug / crash / incorrect behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the report! The more details you provide, the faster I can reproduce and fix it.
        **Please do not upload screenshots of logs** — paste text or share a paste link.

  - type: input
    id: mod_name
    attributes:
      label: Mod name
      placeholder: "e.g. DryIce, HandyCandle..."
    validations:
      required: true

  - type: input
    id: mod_version
    attributes:
      label: Mod version
      placeholder: "e.g. 1.2.3"
    validations:
      required: true

  - type: input
    id: mc_version
    attributes:
      label: Minecraft version
      placeholder: "e.g. 1.20.1"
    validations:
      required: true

  - type: dropdown
    id: loader
    attributes:
      label: Mod loader
      options:
        - Forge
        - NeoForge
        - Fabric
        - Quilt
        - Other / not sure
    validations:
      required: true

  - type: input
    id: loader_version
    attributes:
      label: Loader version
      placeholder: "e.g. Forge 47.3.0"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: What’s the bug? What did you expect to happen instead?
      placeholder: "Describe the issue..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Clear step-by-step instructions help a lot.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / crash report
      description: Paste the relevant error and link the full logs (Pastebin/Gist/etc.)
      placeholder: |
        Full logs link:
        Relevant error (stacktrace):
        ```text
        ...
        ```
    validations:
      required: true

  - type: textarea
    id: modlist
    attributes:
      label: Mod list (if relevant)
      placeholder: "Paste list or provide a link"
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Quick checklist
      options:
        - label: I checked that this is not a duplicate issue
          required: true
        - label: I tested without other mods (if possible)
          required: false
