name: 💡 Feature request
description: Suggest a feature or improvement
title: "[SUGGESTION] "
labels: ["enhancement"]
body:
  - type: input
    id: mod_name
    attributes:
      label: Mod name
    validations:
      required: true

  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
      placeholder: "Describe the feature / change..."
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
      placeholder: "Use-case, balance, QoL, examples."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives / workarounds
      placeholder: "Any other ways to achieve the same goal?"
    validations:
      required: false
